### ISSUE TITLE
1.3-jdk7 is broken

### ISSUE THREAD

**Issue by nlepage** [Zenika/alpine-kotlin#29]
```sh
/ # java -version
java version "1.7.0_181"
OpenJDK Runtime Environment (IcedTea 2.6.14) (Alpine 7.181.2.6.14-r0)
OpenJDK 64-Bit Server VM (build 24.181-b01, mixed mode)
/ # 
/ # 
/ # kotlinc
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/jetbrains/kotlin/preloading/Preloader : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:808)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:442)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:64)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:354)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:348)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:347)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:430)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:323)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)
/ # 

```

**Comment by nlepage** [comment]
No mention in 1.3-M1 release note of discontinued support of JDK7...

**Comment by nlepage** [comment]
JDK8 is necessary for kotlinc since 1.1.2
